database:
  enabled: true
  type: sqlite
  sqlite:
    path: "./app.db"
  show_sql: false
log:
  level: debug # 日志等级  debug,info,waring,error
  filename: ./logs/sms.log

server:
  addr: "0.0.0.0:8080"
  ip_extractor: "X-Real-IP"

App:
  # JWT配置
  JWT:
    # 随机生成一个 32 字节的字符串，推荐使用 openssl rand -base64 32 生成
    Secret: ""
    ExpiresHours: 168 # 7天
  Users:
    # 使用 Bcrypt 加密，默认密码为 admin123，建议首次登录后修改密码
    admin: "$2y$12$7DXcOiX1D59xNTIn5riUKusAPLP88LxxoczWmUT83MBj5EFznbp8a"

  # 串口配置
  Serial:
    # 留空则自动检测，建议首次启动后手动指定
    Port: ""
